INFURA_ENDPOINT_URL = '<INFURA-URL>'
PRIVATE_KEY = '<YOUR-WALLET-ADDRESS>'
PUBLIC_KEY = '<PRIVATE KEY>'
CHANNEL_NAME = '<CHANNEL-NAME>'
TOKEN = '<DISCORD-TOKEN-FOR-BOT>'

HELPFUL_ANSWER = <TOKEN_AMOUNT>
AWESOME_ANSWER = <TOKEN_AMOUNT>

WALLET ={
    '<USER>':'<WALLET-ADDRESSADDRESS>',
   }

